### ISSUE TITLE
Included `apollo-boost` in `sewing-kit.config.js` instead of listing it out

### ISSUE THREAD

**Issue by michelleyschen** [michelleyschen/shopify-app#15]
https://github.com/michelleyschen/shopify-app/pull/12#discussion_r202070561

@GoodForOneFare included `apollo-cache-inmemory` here fail in browser.
<img width="697" alt="with apollo-cache-inmemory in vendor" src="https://user-images.githubusercontent.com/1610169/42641928-b14abc78-85c3-11e8-8b0a-37aa951e83d5.png">
would you have any idea why this is happening?

if this error is resolved, then I think I can just included `apollo-boost` instead of listing each individual module :)

**Comment by GoodForOneFare** [comment]
Just released `@shopify/sewing-kit@0.53.1` with a fix for this.

**Comment by michelleyschen** [comment]
Resolved now using `@shopify/sewing-kit@0.53.1`
