### ISSUE TITLE
style is being loaded in later in dev? (see the flash of unstyled page)

### ISSUE THREAD

**Issue by michelleyschen** [michelleyschen/shopify-app#19]

**Comment by GoodForOneFare** [comment]
I think this is unavoidable due to webpack's dev mode embedding styles inside JS.

web has a workaround for this that just prevents display until the app is rendered:
https://github.com/Shopify/web/blob/f9848c039e44dbe7a6034344416c2626e82ddd82/client/index.tsx#L188
