### ISSUE TITLE
Upgrade typescript to 3.0 

### ISSUE THREAD

**Issue by michelleyschen** [michelleyschen/shopify-app#27]
or at least typescript 2.8.3 (the same as web)
without getting the eslint warning

wait for `eslint-plugin-shopify` release
https://shopify.slack.com/archives/C2ZF294DU/p1533141529000066

**Comment by cartogram** [comment]
@michelleyschen there was a new release of eslint this week, should be gone with an update to the latest version.

**Comment by michelleyschen** [comment]
I saw! I am now waiting for the official release of sewing-kit with this new `eslint-plugin-shopify`
https://github.com/Shopify/sewing-kit/releases (this is a beta release right now)
