### ISSUE TITLE
[Discussion] `mountWithAppContext ` vs `createWithAppMountOptions` (which one to include in this base app?)

### ISSUE THREAD

**Issue by michelleyschen** [michelleyschen/shopify-app#5]
cc @lemonmade @TheMallen

**Comment by lemonmade** [comment]
`createWithAppMountOptions` will just never be appropriately flexible. You can't add React 16.3 context providers, you can't attach any additional properties/ fields to the return result, and you can't do [mount tracking](https://github.com/Shopify/quilt/pull/127).

**Comment by TheMallen** [comment]
Also the name is really obtuse :p
